routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
******************** SITE
********************
*/

Route::view('/', 'site.index')->name('home')->middleware('guest');

Route::get('/caratteristiche', function () {
    return view('site.caratteristiche');
})->name('caratteristiche')->middleware('guest');

Route::get('/vantaggi', function () {
    return view('site.vantaggi');
})->name('vantaggi')->middleware('guest');

Route::prefix('/legal')->group(function () {

    Route::get('/privacy', function () {
        return view('site.legal.privacy');
    })->name('legal.privacy');

    Route::get('/condizioni', function () {
        return view('site.legal.condizioni');
    })->name('legal.condizioni');

    Route::get('/cookies', function () {
        return view('site.legal.cookies');
    })->name('legal.cookies');

});



/*
******************** AUTH
********************
*/

Auth::routes(['verify' => false]);

Route::get('/registrazione', ['as' => 'registrazione', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
Route::POST('/registrazione', ['as' => 'auth.registrazione', 'uses' => 'Auth\RegisterController@register']);

Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::POST('/login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@login']);

//Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::get('/password/email', ['as' => 'auth.password.request.email', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::POST('/password/email', ['as' => 'auth.password.send.link', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);

Route::get('/password/reset', ['as' => 'auth.password.show.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
Route::POST('/password/reset', ['as' => 'auth.password.store.reset', 'uses' => 'Auth\ResetPasswordController@reset']);

Route::get('/conferma', ['as' => 'auth.conferma.email', 'uses' => 'UserController@confermaEmail']);

Route::prefix('/onboarding')->group(function(){
    Route::view('welcome', 'boarding.welcome')->name('boarding.step1');
});

/*
******************** ANNUNCI
********************
*/

Route::prefix('s')->group(function () {
    Route::get('/', ['as' => 'senseria.annunci.search', 'uses' => 'SenseriaController@annunciSearch']);
});


/*
******************** CALENDARIO
********************
*/
Route::prefix('calendario')->group(function () {
    Route::get('/', function() {
        return 'calerndario';
    })->name('calendario');
});


/*
******************** AGENTI
********************
*/
Route::prefix('agenti')->group(function () {
    Route::get('/', function() {
        return 'agenti';
    })->name('agenti');
});


/*
******************** ANNUNCI
********************
*/
Route::prefix('{contratto}')->group(function () {
    Route::prefix('{specifica?}')->group(function () {
        Route::prefix('{comune?}')->group(function () {
            Route::get('/', ['as' => 'senseria.annunci', 'uses' => 'SenseriaController@annunciIndex']);
        });
    });
});

Route::get('{contratto}/{specifica}/{comune}/{codice}', ['as' => 'senseria.annuncio', 'uses' => 'SenseriaController@annunciShow'])->middleware('pubblicita');

app/User.php
<?php

namespace App;

use DB;
use Auth;
use App\Suggerimento;
use App\Scopes\FilterByAttivo;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Contracts\Encryption\DecryptException;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use CyrildeWit\EloquentViewable\Contracts\Viewable;

class User extends Authenticatable  implements Viewable
{
    use InteractsWithViews;

    use Notifiable;

    protected $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'qualifica_id', 'collegio_id', 'categoria_id', 'fullname', 'email', 'email_verified_at', 'password', 'attivo', 'slug', 'activeCampaignId', 'completed_at', 'area_operativa', 'preferences','stripe_id', 'last_four', 'card_brand', 'isadmin', 'tipo'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
        protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'preferences' => 'array'
    ];

    public function getidCriptatoAttribute(){
        return encrypt($this->id);
    }

    public function idDecriptato(){
        try {
            return $decrypted = decrypt($encryptedValue);
        } catch (DecryptException $e) {
            return $e;
        }
    }
    //relazioni

    public function notifiche(){
        return $this->hasMany('App\Notifica', 'destinatario_id');
    }

    public function raccolte(){
        return $this->hasMany('App\Raccolta', 'user_id')->orderBy('updated_at', 'DESC');
    }

    public function raccolteuser(){
        return $this->raccolte()->where('coverable_type', get_class(new User));
    }

    public function raccoltecontenuti(){
        return $this->raccolte()->where('coverable_type', get_class(new Articolo))->orWhere('coverable_type', get_class(new Galleria));
    }

    public function raccolteannunci(){
        return $this->raccolte()->where('coverable_type', get_class(new Annuncio));
    }

    public function raccolta() {
        return $this->morphMany('App\Raccolta', 'coverable');
    }

    public function likes(){
        return $this->hasMany('App\Like', 'user_id');
    }

    public function partecipazioni(){
        return $this->hasMany('App\Partecipazione', 'user_id');
    }

    public function carte(){
        return $this->hasMany('App\Carta', 'user_id');
    }

    public function subscriptions(){
        return $this->hasMany('App\Subscription', 'user_id');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Ruolo', 'user_ruolo', 'user_id', 'ruolo_id');
    }

    public function qualifica()
    {
        return $this->belongsTo('App\Qualifica', 'qualifica_id');
    }

    public function collegio()
    {
        return $this->belongsTo('App\AlboCollegio', 'collegio_id');
    }

    public function categoria()
    {
        return $this->belongsTo('App\Categoria', 'categoria_id');
    }

    public function prestazioni()
    {
        return $this->belongsToMany('App\Prestazione', 'user_prestazione', 'user_id', 'prestazione_id');
    }

    public function abilitazioni()
    {
        return $this->belongsToMany('App\Abilitazione', 'user_abilitazione', 'user_id', 'abilitazione_id');
    }

    public function immobili()
    {
        return $this->hasMany('App\Immobile')->orderBy('updated_at', 'desc');
    }

    public function certificazione()
    {
        return $this->hasOne('App\UserCertificazione', 'user_id');
    }

    public function suggerimenti()
    {
        return $this->belongsToMany('App\Suggerimento', 'user_suggerimento', 'user_id', 'suggerimento_id')->withPivot('visibile');
    }

    public function meta(){
        return $this->hasOne(UserMeta::class, 'user_id');
    }

    public function token()
    {
        return $this->hasMany('App\UserToken', 'user_id');
    }

    public function articoli()
    {
        return $this->hasMany('App\Articolo', 'user_id');
    }

    public function articolipubblicati()
    {
        return $this->hasMany('App\Articolo', 'user_id')->where('pubblicato', 1);
    }

    public function sonoautore()
    {
        return $this->hasMany('App\Immobile', 'user_id');
    }

    public function sonotecnico()
    {
        return $this->hasMany('App\Immobile', 'tecnico_id');
    }

    public function sonoagente()
    {
        return $this->hasMany('App\Immobile', 'agente_id');
    }

    public function candidature(){
        return $this->hasMany('App\Candidatura', 'user_id');
    }

    public function candidatureFilterByAnnuncio($annuncioid){
        return $this->hasMany('App\Candidatura', 'user_id')->whereHas('dettaglio', function($query) use ($annuncioid) {
            $query->where('annuncio_id', $annuncioid);
        })->withoutGlobalScope(FilterByAttivo::class);
    }

    public function annunci_compatibili()
    {
        return $this->hasMany('App\AnnunciCompatibili', 'ricevente_id')->with(['coverable.immobile.specifica.destinazione', 'coverable.immobile.informazione', 'coverable.immobile.user','coverable.immobile.tecnico']);
    }

    public function annunciComeResponsabileTecnico(){
        return $this->hasMany('App\AnnunciCompatibili', 'ricevente_id')->whereHasMorph('coverable', ['App\Annuncio'], function(Builder $query){
            $query->where('type', config('constants.type_annunci.resp_tecnico'));
        });
    }

    public function conversazioni()
    {
        return $this->hasMany('App\Conversazione', 'creatore_id');
    }

    public function sonopartecipe()
    {
        return $this->belongsToMany('App\Conversazione', 'conversazione_user', 'user_id', 'conversazione_id');
    }

    public function gallerie()
    {
        return $this->hasMany('App\Galleria', 'user_id');
    }

    public function galleriepubblicate()
    {
        return $this->hasMany('App\Galleria', 'user_id')->where('pubblicata', 1);
    }

    //FINE RELAZIONI

    public function abbonamento_attuale(){
        return $this->subscriptions()->where('status', 1)->first();
    }


    public function newSubscription($stripe, $customer_id, $stripe_plan){
        return $stripe->subscriptions->create([
            'customer' => $customer_id,
            'items' => [
                ['price' => $stripe_plan],
            ],
        ]);
    }

    public function isProfessionista(){
        return !$this->tipo == 'professionista' ? false : true;
    }

    public function isImpresa(){
        return !$this->tipo == 'impresa' ? false : true;
    }

    public function isAgente(){
        return !$this->tipo == 'agente' ? false : true;
    }

    public function isAdmin(){
        return $this->roles->where('nome', 'admin')->isNotEmpty();
    }

    public function isCertified(){
        return $this->certificazione->where('status', '????')->isNotEmpty();
    }

    public function viewSuggerimento($suggerimento){
        $suggerimento = Suggerimento::where('nome', $suggerimento)->first();
        if($suggerimento) {
            $filterSuggerimento = Auth::user()->suggerimenti->where('id', $suggerimento->id)->first();
            if(!$filterSuggerimento){
                return false;
            }
            return  $filterSuggerimento->pivot->visibile == 1 ? true : false;
        }
        return false;
    }


    public function isInRaccolta(int $raccolta, string $class) {
      return count(Auth::user()->raccolte->where('coverable_id', $raccolta)->where('coverable_type', $class)) == 1;
    }

    public function isInLike(int $like, string $class) {
        return count(Auth::user()->likes->where('coverable_id', $like)->where('coverable_type', $class)) == 1;
    }

    //mutator
    public function getDefaultPaymentMethodAttribute()
    {
        return $this->carte()->where('default', 1)->first();
    }

    public function getNomeCognomeAttribute(){
        return  $this->fullname;
    }

    public function getDisplayNameAttribute(){
        #TO_REVIEW#
        return  $this->tipo == 'professionista' || $this->tipo == 'impresa' ? "<span class=\"qualifica\">{$this->qualifica->nome_pubblico}</span> {$this->nome_cognome}" : "{$this->meta->ragione_sociale}";
    }

    

    public function getComuneAttribute()
    {
        return $this->meta->descrizione_comune;
    }

    public function getInfoAttribute()
    {
        return $this->meta->info_generali;
    }
    
    public function getProvinciaAttribute()
    {
        return $this->info['provincia'];
    }

    public function getCognomeNomeAttribute(){
        return  $this->tipo == 'professionista' ? "{$this->meta->cognome} {$this->meta->nome}" : "{$this->meta->ragione_sociale}";
    }

    public function getNomeAttribute(){
        return  $this->tipo == 'professionista' ? "{$this->meta->nome}" : null;
    }

    public function getCognomeAttribute(){
        return  $this->tipo == 'professionista' ? "{$this->meta->cognome}" : null;
    }

    public function getRagioneSocialeAttribute(){
        return  $this->tipo == 'impresa' ? "{$this->meta->ragione_sociale}" : null;
    }

    public function getRappresentanteAttribute(){
        #TO_REVIEW#
        return !is_null($this->user_meta_impresa()->first()->rappresentante) ? unserialize($this->user_meta_impresa()->first()->rappresentante) : [];
    }

    public function getNomeRappresentanteAttribute(){
        #TO_REVIEW#
        return array_key_exists('nome', $this->rappresentante) ? $this->rappresentante['nome'] : null;
    }

    public function getCognomeeRappresentanteAttribute(){
        #TO_REVIEW#
        return array_key_exists('cognome', $this->rappresentante) ? $this->rappresentante['cognome'] : null;
    }

resources/views/app/conversazioni/archivio.blade.php
@extends('app.layouts.master')

@section('title', 'Conversazioni')
@section('bodyclass')@parent {{ 'conversazioni' }}@endsection

@section('headertitle')
    @component('app.components.headertitle')
        Conversazioni
    @endcomponent 
@endsection


@section('headersearch')
<form class="item item--center ">
<div class="form-group form-group-search">
    <input type="text" class="form-input input-lg input-search input-rounded" placeholder="Cerca conversazione">
    <svg><use xlink:href="#icon-search"></use></svg>
</div>
</form>
@endsection



@section('headermenu')
    @component('app.components.headermenu')
    <li>
        <a href="{{ route('conversazioni.archivio') }}" class="tooltip  @if(Route::currentRouteName() == 'conversazioni.archivio') {{ 'current' }} @endif" data-tooltip="Archivio conversazioni">Archivio</a>
    </li>
    @endcomponent
@endsection


@section('content')
            <ul class="list">
            {{-- @for ($i = 0; $i < 24; $i++)
                <li>
                    <a href="{{ route('conversazione')}}">
                        <small>13-01-2020</small>
                        <h4>Oggetto del messaggio {{ $i }}</h4>
                        <small>{{ '@' }}Geometra Andrea Ferri</small>
                    </a>
                </li>
                
            @endfor --}}
            @foreach ($user->sonopartecipe as $conversazione)
                <li>
                    <a href="{{ route('conversazione', $conversazione)}}">
                        <small>13-01-2020</small>
                        <h4>{{ config('constants.oggetto-annunci')[$conversazione->coverable->type] }} </h4>
                        @foreach ($conversazione->users as $user)
                            <small>@ {!! $user->display_name !!}</small><br>
                        @endforeach
                        
                    </a>
                </li>
            @endforeach
        </ul>
@endsection

resources/views/app/conversazioni/index.blade.php
@extends('app.layouts.master')

@section('title', 'Conversazioni')
@section('bodyclass')@parent {{ 'conversazioni' }}@endsection

@section('headertitle')
    @component('app.components.headertitle')
        Conversazioni
        <a href="{{ url(route('articoli.nuovo')) }}" class="btn-add tooltip tooltip-right" data-tooltip="Nuova conversazione">+</a>
    @endcomponent
@endsection


@section('headersearch')
<form class="item item--center ">
<div class="form-group form-group-search">
    <input type="text" class="form-input input-lg input-search input-rounded" placeholder="Cerca conversazione">
    <svg><use xlink:href="#icon-search"></use></svg>
</div>
</form>
@endsection

@section('headermenu')
    @component('app.components.headermenu')
    <li>
        <a href="{{ route('conversazioni.archivio') }}" class="tooltip  @if(Route::currentRouteName() == 'conversazioni.archivio') {{ 'current' }} @endif" data-tooltip="Archivio conversazioni">Archivio</a>
    </li>
    @endcomponent
@endsection

@section('content')
        @if($conversazioni)
            <div class="columns">
                @foreach ($conversazioni as $conversazione)

                    <div class="column col-12 p10">
                        <a href="{{ route('conversazione', $conversazione)}}">
                            <!--<small>{{  $conversazione->messaggi()->latest('data')->first() }}</small>-->
                            @if($conversazione->coverable_type == get_class(new App\User))
                                <h4>Contatto con {{ $conversazione->coverable->fullname }}</h4>
                            @endif
                            
                            @if($conversazione->coverable->type == 'immobili') 
                            <h4>{{ config('constants.oggetto-annunci')[$conversazione->coverable->type] }}</h4>
                            {{ $conversazione->coverable->immobile->codice}}
                            @endif

                            @if($conversazione->coverable->type == 'acquirenti') 
                            <h4>{{ config('constants.oggetto-annunci')[$conversazione->coverable->type] }}</h4>
                           {{ $conversazione->coverable->immobile->codice}}
                            @endif
                            
                            @foreach ($conversazione->users as $user)
                                <small>@ {!! $user->display_name !!}</small><br>
                            @endforeach
                        </a>
                    </div>
                @endforeach
            </div>
        @else

                    nessuna conversazione attiva

        @endif
@endsection

resources/views/app/conversazioni/show.blade.php
@extends('app.layouts.master')

@section('title', 'Conversazioni')
@section('bodyclass')@parent {{ 'conversazione' }}@endsection

@section('header')
@endsection

@section('content')
    <div class="conversazione_sidebar">
            <div class="conversazione_sidebar_header">
            <small><a href="{{ route('conversazioni')}}"><svg><use xlink:href="#icon-left"></use></svg> Conversazioni</a></small>
            <button data-toggle="#conversazionesidebar">•••</button>
            </div>
            <div id="conversazionesidebar" class="conversazione_sidebar_body">
            <small>Oggetto conversazione</small>
            <a href="{{ route('annuncio', $conversazione->coverable->codice) }}"><h1>{{ $conversazione->coverable->immobile->codice}}</h1></a>

            @if($conversazione->users)
            <small>Partecipanti</small>
                @foreach($conversazione->users as $user)
                <h3>{{ $user->fullname}}</h3>
                @endforeach
            @endif
            
            <div class="form-group">
            <label class="form-label">Aggiungi utente</label>
            <select class="select"></select>
            </div>
            </div>
            <div class="conversazione_sidebar_footer">
            <small><a href="">Archivia conversazione</a></small><br/>
            <small><a href="">Esporta conversazione</a></small>
            </div>
    </div>
    <div class="conversazione_content" id="conversazione_content" data-sender="{{ Auth::id() }}">

        <div class="overlay"></div>

        <div class="messaggi">
            @foreach ($conversazione->messaggi as $messaggio)

            <div class="messaggio messaggio--{{ $messaggio->from == Auth::id() ? 'right' : 'left' }}" data-messaggio="{{ $messaggio->id }}">
                <div class="messaggio__content">
                <div class="messaggio__header">{!! $messaggio->user->display_name !!} <div class="dropdown mlauto"><a href="" class="dropdown-toggle">•••</a>
                                                                    <ul class="dropdown-menu">
                                                                        <li><a href="#">Elimina per me</a></li>
                                                                    </ul></div>
                </div>
                    {!! $messaggio->messaggio !!}
                <time>{!! $messaggio->data->format('H:i') !!}</time>
                </div>
            </div>
            
            @endforeach
        </div>
    </div>
    <div class="conversazione_input">
        <textarea id="corpo"></textarea>
        <input type="submit" id="send-message" data-conversazione="{!! $conversazione->id !!}" class="btn btn-primary nopreloader" value="invia">
    </div>
@endsection


@section('footerlegal')
@endsection

@section('footerjs_after')

<script>

    // Enable pusher logging - don't include this in production
    // Pusher.logToConsole = true;
    var input = document.getElementById("corpo");
        input.addEventListener("keyup", function(event) {
        if (event.keyCode === 13) {
            event.preventDefault();
            document.getElementById("send-message").click();
            return false;
        }
    });

  </script>
@endsection