routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
******************** SITE
********************
*/

Route::view('/', 'site.index')->name('home')->middleware('guest');

Route::get('/caratteristiche', function () {
    return view('site.caratteristiche');
})->name('caratteristiche')->middleware('guest');

Route::get('/vantaggi', function () {
    return view('site.vantaggi');
})->name('vantaggi')->middleware('guest');

Route::prefix('/legal')->group(function () {

    Route::get('/privacy', function () {
        return view('site.legal.privacy');
    })->name('legal.privacy');

    Route::get('/condizioni', function () {
        return view('site.legal.condizioni');
    })->name('legal.condizioni');

    Route::get('/cookies', function () {
        return view('site.legal.cookies');
    })->name('legal.cookies');

});



/*
******************** AUTH
********************
*/

Auth::routes(['verify' => false]);

Route::get('/registrazione', ['as' => 'registrazione', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
Route::POST('/registrazione', ['as' => 'auth.registrazione', 'uses' => 'Auth\RegisterController@register']);

Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::POST('/login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@login']);

//Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::get('/password/email', ['as' => 'auth.password.request.email', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::POST('/password/email', ['as' => 'auth.password.send.link', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);

Route::get('/password/reset', ['as' => 'auth.password.show.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
Route::POST('/password/reset', ['as' => 'auth.password.store.reset', 'uses' => 'Auth\ResetPasswordController@reset']);

Route::get('/conferma', ['as' => 'auth.conferma.email', 'uses' => 'UserController@confermaEmail']);

Route::prefix('/onboarding')->group(function(){
    Route::view('welcome', 'boarding.welcome')->name('boarding.step1');
});

/*
******************** ANNUNCI
********************
*/

Route::prefix('s')->group(function () {
    Route::get('/', ['as' => 'senseria.annunci.search', 'uses' => 'SenseriaController@annunciSearch']);
});


/*
******************** CALENDARIO
********************
*/
Route::prefix('calendario')->group(function () {
    Route::get('/', function() {
        return 'calerndario';
    })->name('calendario');
});


/*
******************** AGENTI
********************
*/
Route::prefix('agenti')->group(function () {
    Route::get('/', function() {
        return 'agenti';
    })->name('agenti');
});


/*
******************** ANNUNCI
********************
*/
Route::prefix('{contratto}')->group(function () {
    Route::prefix('{specifica?}')->group(function () {
        Route::prefix('{comune?}')->group(function () {
            Route::get('/', ['as' => 'senseria.annunci', 'uses' => 'SenseriaController@annunciIndex']);
        });
    });
});

Route::get('{contratto}/{specifica}/{comune}/{codice}', ['as' => 'senseria.annuncio', 'uses' => 'SenseriaController@annunciShow'])->middleware('pubblicita');

app/Galleria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use CyrildeWit\EloquentViewable\Contracts\Viewable;

class Galleria extends Model implements Viewable
{

    use InteractsWithViews;

    protected $table = 'gallerie';

    public $timestamps = false;

    protected $fillable = ['user_id', 'immobile_id', 'titolo', 'crediti', 'slug', 'token', 'pubblicata', 'codice'];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function immagini()
    {
        return $this->belongsToMany('App\Immagine', 'galleria_immagine', 'galleria_id', 'immagine_id');
    }

    public function associati()
    {
        return $this->belongsToMany('App\User', 'user_galleria', 'galleria_id', 'user_id');
    }

    public function partecipazioni(){
        return $this->morphMany('App\Partecipazione', 'modelable');
    }

    public function like()
    {
        return $this->morphMany('App\Like', 'coverable');
    }

    /** SCOPE **/
    public function scopePubblicate($query)
    {
        return $query->where('pubblicata', 1);
    }

    /** MUTATOR **/
    public function getImmagineEvidenzaAttribute(){
        return $this->immagini()->first();
    }

    

}

resources/views/app/partials/headermenugallerie.blade.php
<li class="has-submenu"><a href="#" @if(Request::is('gallerie') || Request::is('gallerie/*')) class="current" @endif><svg><use xlink:href="#icon-gallerie"></use></svg> <span class="label">Gallerie</span></a>
    <ul class="submenu">
        <li><a href="{{ route('gallerie') }}" title="Gallerie recenti" @if(Request::is('gallerie')) class="current" @endif>Recenti</a></li>
        <li><a href="{{ route('gallerie.popolari') }}" title="Gallerie popolari" @if(Request::is('gallerie/popolari')) class="current" @endif>Popolari</a></li>
    </ul>
</li>

@if(Auth::check())
<li class="has-submenu gestione"><a href="#"><svg><use xlink:href="#icon-edit"></use></svg> <span class="label">Gestione</span></a>
    <ul class="submenu submenu-right">
        <li><a href="{!! route('gallerie.gestione') !!}" title="Le mie gallerie" @if(Request::is('gallerie/gestione')) class="current" @endif>Le mie gallerie</a></li>
        <li><a href="{{ route('gallerie.gestione.tag') }}" title="Gallerie dove sono taggato" @if(Request::is('gallerie/gestione/tag')) class="current" @endif>Dove sono taggato</a></li>
    </ul>
</li>
@endif

resources/views/app/partials/menunotifiche.blade.php
<ul class="inline-nav scrollmenu text-center text-left--md">
    <li><a href="{!! route('account.notifiche') !!}" title="Tutte le notifiche" @if(Route::currentRouteName() == 'account.notifiche') class="current" @endif>Tutte</a></li>
    <li><a href="{!! route('account.notifiche') !!}" title="Tutte le notifiche" @if(Route::currentRouteName() == 'account.notifiche.profilo') class="current" @endif>Profilo</a></li>
    <li><a href="{!! route('account.notifiche') !!}" title="Tutte le notifiche" @if(Route::currentRouteName() == 'account.notifiche.immobili') class="current" @endif>Immobili</a></li>
    <li><a href="{!! route('account.notifiche') !!}" title="Tutte le notifiche" @if(Route::currentRouteName() == 'account.notifiche.annunci') class="current" @endif>Annunci</a></li>
    <li><a href="{!! route('account.notifiche') !!}" title="Tutte le notifiche" @if(Route::currentRouteName() == 'account.notifiche.contenuti') class="current" @endif>Contenuti</a></li>
    <li class="right">
        <form>
            <div class="form-group form-group-search">
            <input type="text" class="form-input input-lg input-rounded input-search" placeholder="Cerca notifiche">
            <svg><use xlink:href="#icon-search"></use></svg>
            </div>
        </form>
    </li>
</ul>

resources/views/app/partials/menusettingsabbonamento.blade.php
<ul class="inline-nav scrollmenu text-center text-left--md">
    <li><a href="{!! route('account.abbonamento') !!}" title="Riepilogo abbonamento" @if(Route::currentRouteName() == 'account.abbonamento') class="current" @endif>Riepilogo</a></li>
    <li><a href="{!! route('account.abbonamento.piani') !!}" title="Modifica abbonamento" @if(Route::currentRouteName() == 'account.abbonamento.piani') class="current" @endif>Modifica</a></li>
</ul>

resources/views/app/partials/menusettingsimpostazioni.blade.php
<ul class="inline-nav scrollmenu text-center text-left--md">
    <li><a href="{!! route('account.impostazioni') !!}" title="Impostazione Notifiche" @if(Route::currentRouteName() == 'account.impostazioni') class="current" @endif>Notifiche</a></li>
    <li><a href="{!! route('account.impostazioni.password') !!}" title="Impostazione Password" @if(Route::currentRouteName() == 'account.impostazioni.password') class="current" @endif>Password</a></li>
    <li><a href="{!! route('account.impostazioni.privacy') !!}" title="Impostazione Privacy" @if(Route::currentRouteName() == 'account.impostazioni.privacy') class="current" @endif>Privacy</a></li>
    <li><a href="{!! route('account.impostazioni.avanzate') !!}" title="Impostazione Avanzate" @if(Route::currentRouteName() == 'account.impostazioni.avanzate') class="current" @endif>Avanzate</a></li>
</ul>

resources/views/app/partials/menusettingsstatistiche.blade.php
<ul class="inline-nav scrollmenu text-center text-left--md">
    <li><a href="{!! route('account.statistiche') !!}" title="Statistiche generali" @if(Route::currentRouteName() == 'account.statistiche') class="current" @endif>Generali</a></li>
    <li><a href="{!! route('account.statistiche.profilo') !!}" title="Statistiche profilo" @if(Route::currentRouteName() == 'account.statistiche.profilo') class="current" @endif>Profilo</a></li>
    <li><a href="{!! route('account.statistiche.articoli') !!}" title="Statistiche articoli" @if(Route::currentRouteName() == 'account.statistiche.articoli') class="current" @endif>Articoli</a></li>
    <li><a href="{!! route('account.statistiche.gallerie') !!}" title="Statistiche gallerie" @if(Route::currentRouteName() == 'account.statistiche.gallerie') class="current" @endif>Gallerie</a></li>
</ul>

resources/views/app/partials/previewNotifica.blade.php
<div class="notifica {{ $notifica->readed ? 'readed' : '' }}">
    <div class="notifica-action">
        @if(!$notifica->readed)
            <button class="unreaded" data-action="signNotificationAsReaded" data-id="{{ encrypt($notifica->id) }}"></button>
        @endif
   </div>
    <a href="{{ url($notifica->route)}}">
        <div class="notifica-header">
            <div class="date">
            {{ Custom::createDate($notifica->created_at) }}
            </div>
            <div class="action">
                <button class="delete {{  $notifica->readed ? 'show' : '' }}" data-action="deleteNotification" data-id="{{ encrypt($notifica->id) }}">elimina</button>
            </div>
        </div>
        <div class="notifica-body">
        {!! $notifica->messaggio !!}
        </div>
    </a>
</div>

resources/views/app/partials/previewarticolo.blade.php
<div class="articolo__preview card">
    <a href="{{ route('articolo', ['categoria' => $articolo->categoria->slug, 'slug' => $articolo->slug ]) }}" title="Apri {{ $articolo->titolo }}" class="img-container">
    <img src="https://picsum.photos/360/220" alt="{{ $articolo->titolo }}">
    </a>
    <h4><a href="{{ route('articolo', ['categoria' => $articolo->categoria->slug, 'slug' => $articolo->slug ]) }}" title="Apri {{ $articolo->titolo }}">{{ Custom::formatTitle($articolo->titolo) }}</a></h4>
    
    <footer>
        @include('includes.partials.userpopover', ['user' => $articolo->user, 'linkable' => true])
       
        @include('includes.partials.counterviews', ['data' => $articolo])

        @include('includes.partials.counterraccolte', ['data' => $articolo, 'class' => get_class(new App\Articolo)])

        @include('includes.partials.counterlikes', ['data' => $articolo, 'class' => get_class(new App\Articolo)])

    </footer>
</div>

resources/views/app/partials/previewgalleria.blade.php
<div class="articolo__preview card">
    <a href="{{route('galleria', $galleria->slug)}}" class="img-container">
        <span class="img-counter">{{ count($galleria->immagini)}}</span>

        <img
            src="{{Storage::url('gallerie/'.$galleria->user_id.'/'.$galleria->codice.'/crop/'.$galleria->immagine_evidenza->filename)}}"
            alt="{{ $galleria->titolo }}">
    </a>
    <h4><a href="{{route('galleria', $galleria->slug)}}">{{ $galleria->titolo }}</a></h4>
    <footer>
        @include('includes.partials.userpopover', ['user' => $galleria->user, 'linkable' => true])

        @include('includes.partials.counterviews', ['data' => $galleria])

        @include('includes.partials.counterraccolte', ['data' => $galleria, 'class' => get_class(new App\Galleria)])

        @include('includes.partials.counterlikes', ['data' => $galleria, 'class' => get_class(new App\Galleria)])
    </footer>
</div>

resources/views/app/partials/previewimmobile.blade.php
<a class="card card--immobile" href="{{ route('immobile', $immobile) }}">

    <div class="card--header">
        {{ $immobile->specifica->nome_pubblico }}  @if($immobile->informazione) <span class="immobile-mq"> {{ $immobile->informazione->metri_quadri }}<span class="mq">m<sup>2</sup></span> </span> @endif
        @if($immobile->annuncioVendita)
                <span class="badge badge--success badge--xs mlauto">In pubblicità</span>
        @endif
        
    </div>

    <div class="columns">

        <div class="column col-9 text-left">
            <div class="card--title">
                <strong>{{ $immobile->nome }}</strong> @if(!$immobile->informazione) <svg class="icon--25"><use xlink:href="#icon-color-attention"></use></svg>@endif
            </div>
            @if($immobile->informazione && $immobile->informazione->comune)
            <div class="card--location">
                <svg class="icon--15 mr1"><use xlink:href="#icon-marker"></use></svg> {{ $immobile->informazione->comune }} {{ $immobile->informazione->provincia }}
            </div>
            @endif

            <div class="immobile-agente">
                @if($immobile->agente)
                <span class="badge badge--xs"><svg><use xlink:href="#icon-agente"></use></svg> {{ $immobile->agente->nomecognome }}</span>
                @endif
            </div>

        </div>

        <div class="column col-3 text-right">
            <svg class="destinazione"><use xlink:href="#destinazione-{{ strtolower($immobile->destinazione->nome) }}"></use></svg>
        </div>

    </div>

    <div class="card--footer">
            @if($immobile->tecnico)
                <div class="immobile-responsabiletecnico">

                    <div class="responsabiletecnico-name">
                        <svg><use xlink:href="#icon-responsabile"></use></svg>
                        <span class="qualifica">{{ $immobile->tecnico->qualifica->nome_pubblico }} </span>
                        <span class="nome">{{ $immobile->tecnico->nomecognome }}</span>
                    </div>

                    <div class="mlauto pr3">
                        @php
                            $rand = rand(0, 100);
                        @endphp
                        <div class="chart-container tooltip" data-tooltip="Stato completamento">
                            <div class="chart chart--lg" data-percent="{{ $rand }}" data-scale-color="#42d212"></div>
                            <span class="chart-percentage"><span class="perc_value">{{ $rand }}</span><span class="perc_sign">%</span></span>
                        </div>
                    </div>

                </div>

            @elseif($immobile->annuncioRespTecnico)
                <div class="immobile-annuncio">
                    Annuncio responsabile tecnico
                </div>
            @else
                <div class="immobile-noresult">
                    Nessun Responsabile tecnico
                </div>
            @endif

    </div>

</a>

resources/views/app/partials/searchformacquirenti.blade.php
<form action="{{ route('acquirenti.search') }}" class="item item--center  sendOnEnter canLeavePage" method="get">
    <div class="form-group form-group-search">
    <input type="text" name="s" class="form-input input-lg input-search input-rounded" placeholder="Cerca tra i tuoi acquirenti" value="">
        <svg><use xlink:href="#icon-search"></use></svg>
    </div>
</form>

resources/views/app/partials/searchformgallerie.blade.php
<form class="item item--center sendOnEnter canLeavePage">
    <div class="form-group form-group-search">
        <input type="text" class="form-input input-lg input-search input-rounded" placeholder="Cerca galleria">
        <svg><use xlink:href="#icon-search"></use></svg>
    </div>
</form>

resources/views/app/partials/searchformimmobili.blade.php
<form action="{{ route('immobili.search') }}" class="item item--center sendOnEnter canLeavePage" method="get">
    <div class="form-group form-group-search">
        <input type="text" name="s" class="form-input input-lg input-search input-rounded" placeholder="Cerca tra i tuoi immobili">
        <svg><use xlink:href="#icon-search"></use></svg>
    </div>
</form>

resources/views/app/partials/titleimmobile.blade.php
@php /* @slot('back'){{ route('immobili') }} @endslot  */ @endphp
<a href="{{ route('immobile', $immobile) }}" title="Riepilogo {{ $immobile->nome }}" class="immobile-title">{{ $immobile->nome }}</a>
@isset($childs) @foreach($childs as $child) <span class="weight-300">/ {{ $child }}</span> @endforeach @endif

resources/views/app/partials/titlesopralluogo.blade.php
@php /* @slot('back'){{ route('immobile', $immobile) }}@endslot */ @endphp
<a href="{{ route('immobile', $immobile) }}" title="{{ $immobile->nome }}" class="weight-300">{{ $immobile->nome }}</a> / <a href="{{ route('immobile.sopralluogo', $immobile) }}" title="Sopralluogo {{ $immobile->nome }}">Sopralluogo</a>
@isset($childs) @foreach($childs as $child) <span class="weight-300">/ {{ $child }}</span> @endforeach @endif